# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

RESCOMP = windres
INCLUDES += -Iinclude -I. -I/usr/include/postgresql
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lsqlite3 -lpq -lz
LDDEPS +=
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/mqtt_sub_client
OBJDIR = obj/Debug
DEFINES += -DVERSION=\"2.0.13\" -DWITH_THREADING -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g
ALL_LDFLAGS += $(LDFLAGS) -pthread -ldl

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/mqtt_sub_client
OBJDIR = obj/Release
DEFINES += -DVERSION=\"2.0.13\" -DWITH_THREADING -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2
ALL_LDFLAGS += $(LDFLAGS) -s -pthread -ldl

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/actions.o
GENERATED += $(OBJDIR)/alias_mosq.o
GENERATED += $(OBJDIR)/cJSON.o
GENERATED += $(OBJDIR)/cJSON_Utils.o
GENERATED += $(OBJDIR)/callbacks.o
GENERATED += $(OBJDIR)/connect.o
GENERATED += $(OBJDIR)/handle_auth.o
GENERATED += $(OBJDIR)/handle_connack.o
GENERATED += $(OBJDIR)/handle_disconnect.o
GENERATED += $(OBJDIR)/handle_ping.o
GENERATED += $(OBJDIR)/handle_pubackcomp.o
GENERATED += $(OBJDIR)/handle_publish.o
GENERATED += $(OBJDIR)/handle_pubrec.o
GENERATED += $(OBJDIR)/handle_pubrel.o
GENERATED += $(OBJDIR)/handle_suback.o
GENERATED += $(OBJDIR)/handle_unsuback.o
GENERATED += $(OBJDIR)/helpers.o
GENERATED += $(OBJDIR)/logging_mosq.o
GENERATED += $(OBJDIR)/loop.o
GENERATED += $(OBJDIR)/memory_mosq.o
GENERATED += $(OBJDIR)/messages_mosq.o
GENERATED += $(OBJDIR)/misc_mosq.o
GENERATED += $(OBJDIR)/mosquitto.o
GENERATED += $(OBJDIR)/mqtt_sub_client.o
GENERATED += $(OBJDIR)/net_mosq.o
GENERATED += $(OBJDIR)/net_mosq_ocsp.o
GENERATED += $(OBJDIR)/options.o
GENERATED += $(OBJDIR)/packet_datatypes.o
GENERATED += $(OBJDIR)/packet_mosq.o
GENERATED += $(OBJDIR)/property_mosq.o
GENERATED += $(OBJDIR)/read_handle.o
GENERATED += $(OBJDIR)/send_connect.o
GENERATED += $(OBJDIR)/send_disconnect.o
GENERATED += $(OBJDIR)/send_mosq.o
GENERATED += $(OBJDIR)/send_publish.o
GENERATED += $(OBJDIR)/send_subscribe.o
GENERATED += $(OBJDIR)/send_unsubscribe.o
GENERATED += $(OBJDIR)/socks_mosq.o
GENERATED += $(OBJDIR)/srv_mosq.o
GENERATED += $(OBJDIR)/strings_mosq.o
GENERATED += $(OBJDIR)/sts_queue.o
GENERATED += $(OBJDIR)/thread_mosq.o
GENERATED += $(OBJDIR)/time_mosq.o
GENERATED += $(OBJDIR)/timer.o
GENERATED += $(OBJDIR)/tls_mosq.o
GENERATED += $(OBJDIR)/utf8_mosq.o
GENERATED += $(OBJDIR)/util_mosq.o
GENERATED += $(OBJDIR)/util_topic.o
GENERATED += $(OBJDIR)/will_mosq.o
OBJECTS += $(OBJDIR)/actions.o
OBJECTS += $(OBJDIR)/alias_mosq.o
OBJECTS += $(OBJDIR)/cJSON.o
OBJECTS += $(OBJDIR)/cJSON_Utils.o
OBJECTS += $(OBJDIR)/callbacks.o
OBJECTS += $(OBJDIR)/connect.o
OBJECTS += $(OBJDIR)/handle_auth.o
OBJECTS += $(OBJDIR)/handle_connack.o
OBJECTS += $(OBJDIR)/handle_disconnect.o
OBJECTS += $(OBJDIR)/handle_ping.o
OBJECTS += $(OBJDIR)/handle_pubackcomp.o
OBJECTS += $(OBJDIR)/handle_publish.o
OBJECTS += $(OBJDIR)/handle_pubrec.o
OBJECTS += $(OBJDIR)/handle_pubrel.o
OBJECTS += $(OBJDIR)/handle_suback.o
OBJECTS += $(OBJDIR)/handle_unsuback.o
OBJECTS += $(OBJDIR)/helpers.o
OBJECTS += $(OBJDIR)/logging_mosq.o
OBJECTS += $(OBJDIR)/loop.o
OBJECTS += $(OBJDIR)/memory_mosq.o
OBJECTS += $(OBJDIR)/messages_mosq.o
OBJECTS += $(OBJDIR)/misc_mosq.o
OBJECTS += $(OBJDIR)/mosquitto.o
OBJECTS += $(OBJDIR)/mqtt_sub_client.o
OBJECTS += $(OBJDIR)/net_mosq.o
OBJECTS += $(OBJDIR)/net_mosq_ocsp.o
OBJECTS += $(OBJDIR)/options.o
OBJECTS += $(OBJDIR)/packet_datatypes.o
OBJECTS += $(OBJDIR)/packet_mosq.o
OBJECTS += $(OBJDIR)/property_mosq.o
OBJECTS += $(OBJDIR)/read_handle.o
OBJECTS += $(OBJDIR)/send_connect.o
OBJECTS += $(OBJDIR)/send_disconnect.o
OBJECTS += $(OBJDIR)/send_mosq.o
OBJECTS += $(OBJDIR)/send_publish.o
OBJECTS += $(OBJDIR)/send_subscribe.o
OBJECTS += $(OBJDIR)/send_unsubscribe.o
OBJECTS += $(OBJDIR)/socks_mosq.o
OBJECTS += $(OBJDIR)/srv_mosq.o
OBJECTS += $(OBJDIR)/strings_mosq.o
OBJECTS += $(OBJDIR)/sts_queue.o
OBJECTS += $(OBJDIR)/thread_mosq.o
OBJECTS += $(OBJDIR)/time_mosq.o
OBJECTS += $(OBJDIR)/timer.o
OBJECTS += $(OBJDIR)/tls_mosq.o
OBJECTS += $(OBJDIR)/utf8_mosq.o
OBJECTS += $(OBJDIR)/util_mosq.o
OBJECTS += $(OBJDIR)/util_topic.o
OBJECTS += $(OBJDIR)/will_mosq.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking mqtt_sub_client
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning mqtt_sub_client
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/cJSON.o: cjson/cJSON.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cJSON_Utils.o: cjson/cJSON_Utils.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/actions.o: lib/actions.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/alias_mosq.o: lib/alias_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/callbacks.o: lib/callbacks.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/connect.o: lib/connect.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_auth.o: lib/handle_auth.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_connack.o: lib/handle_connack.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_disconnect.o: lib/handle_disconnect.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_ping.o: lib/handle_ping.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_pubackcomp.o: lib/handle_pubackcomp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_publish.o: lib/handle_publish.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_pubrec.o: lib/handle_pubrec.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_pubrel.o: lib/handle_pubrel.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_suback.o: lib/handle_suback.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/handle_unsuback.o: lib/handle_unsuback.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/helpers.o: lib/helpers.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/logging_mosq.o: lib/logging_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/loop.o: lib/loop.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/memory_mosq.o: lib/memory_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/messages_mosq.o: lib/messages_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/misc_mosq.o: lib/misc_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mosquitto.o: lib/mosquitto.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/net_mosq.o: lib/net_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/net_mosq_ocsp.o: lib/net_mosq_ocsp.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/options.o: lib/options.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/packet_datatypes.o: lib/packet_datatypes.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/packet_mosq.o: lib/packet_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/property_mosq.o: lib/property_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/read_handle.o: lib/read_handle.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/send_connect.o: lib/send_connect.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/send_disconnect.o: lib/send_disconnect.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/send_mosq.o: lib/send_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/send_publish.o: lib/send_publish.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/send_subscribe.o: lib/send_subscribe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/send_unsubscribe.o: lib/send_unsubscribe.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/socks_mosq.o: lib/socks_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/srv_mosq.o: lib/srv_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/strings_mosq.o: lib/strings_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/thread_mosq.o: lib/thread_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/time_mosq.o: lib/time_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/tls_mosq.o: lib/tls_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/utf8_mosq.o: lib/utf8_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/util_mosq.o: lib/util_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/util_topic.o: lib/util_topic.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/will_mosq.o: lib/will_mosq.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/sts_queue.o: queue/sts_queue.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mqtt_sub_client.o: subscribe/mqtt_sub_client.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/timer.o: timer/timer.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif